### DISCUSSION TITLE
JK-BMS chargeEnabled / dischargeEnabled writeable über MQTT

### DISCUSSION THREAD

**Discussion by volkerg99** [hoylabs/OpenDTU-OnBattery#1697] [Ideas]
Ich würde gern  die Ladung und Entladung im BMS via Skript schalten können. So könnte das BMS immer noch als "Notaus" und nicht als Schalter fungieren. Beispiel: BMS Grenze beim Laden: 3,5V bei der höchsten Zelle. Beim Entladen 2,9V bei der niedrigsten Zelle. Per Skript möchte ich aber die Ladung bereits bei 3,45V/Zelle und die Entladung bei 2,95V abschalten. 
Was haltet ihr davon?

**Comment by rs3hc** [comment]
Ich finde das auch sinnvoll.

Aber ob das vom BMS überhaupt unterstützt wird ist fraglich.
Immerhin kannst du das über die BT App auch nur nach den Password.

**Reply by volkerg99** [reply]
Lt. dem Dokument https://github.com/syssi/esphome-jk-bms/blob/main/docs/pb2a16s20p/BMS%20RS485%20Modbus%20V1.1.pdf sind die beiden rw-Felder. Über Python habe ich zumindest bisher ein paar Register auslesen können. Nur das Schreiben ist mir noch nicht gelungen. 

Edit: Es handelt sich bei meinem BMS um eines aus der PB-Reihe

**Reply by schlimmchen** [reply]
> Über Python habe ich zumindest bisher ein paar Register auslesen können.

Herzlichen Glückwunsch.

Die Anbindung des JK BMS ist über das proprietäre
![image](https://github.com/user-attachments/assets/834ffd3c-54e0-4dda-a90b-3585775b4a5e)
implementiert. Modbus sprechen wir nicht über RS485.

**Reply by volkerg99** [reply]
Ist klar, meinte ja auch nur die Doku, nach der die beiden rw sind. Dann müsste ea ja auch auf andere Wege gehen.

Edit: Es sei denn das Protokoll weicht schon bei solchen Punkten ab.

**Reply by rs3hc** [reply]
Ich verweise hier mal auf einen Beitrag aus der Akkudoktor Forum.

https://akkudoktor.net/t/jkbms-charge-discharge-via-rs485-schalten-update-loesung-via-ble/25086

‐-----------------‐‐-------

Beim neuen JK-BMS Inverter Version geht das über ModBus-RS485. Über die BT App kann man das auch ein/ausschalten.

Ob man das "mißbrauchen" kann ist eine andere Frage. ich denke das der BMS Hersteller die MOSFETs und deren Logik schon so entwickelt haben sollten das das Schalten gefahrlos funktionieren sollte. Das BMS muß sich ja auch darauf verlassen können.

Es sind diese Register (HEX'adezimal und DWord = 32Bit Register):

- 0x1070 Wert 0 oder 1 für Charge Schalter
- 0x1074 Wert 0 oder 1 für Discharge Schalter
- 0x1078 Wert 0 oder 1 für Balance Schalter
- 0x1114 Bit 9 (Wert 512) für Float Modus, dieses Register "Flags" enthält noch mehr Bits für andere Schalter, die gleichen wie in der BT App.


Ich steuere direkt über USB-RS485 Dongle meine beiden JK-BMS aus HomeAssistant an. Im Anhang meine YAML Konfiguration dafür. Da du mit ESPHome arbeiten möchtest kannst du mit leichten Änderungen das sicherlich portieren. Es gibt zwischen ModBus HA zu ESPHome ein par kleinere Unterschiede, besonders bei der Ansteuerung von Bitfeldern, da ist ESPHome leistungsfähiger und man kann mit weniger Trickserei arbeiten.

```
switch:
  - platform: template
    switches:
      battery_1_charge_enable:
        friendly_name: "Battery 1 charge enable"
        unique_id: "battery_1_charge_enable"
        value_template: "{{ int(states('sensor.battery_1_charge_enable'), 0) == 1 }}"
        turn_on:
          service: modbus.write_register
          data_template:
            hub: "JKBMS1"
            slave: 0
            address: 0x1070
            value: [0, 1]
        turn_off:
          service: modbus.write_register
          data_template:
            hub: "JKBMS1"
            slave: 0
            address: 0x1070
            value: [0, 0]
```
