### DISCUSSION TITLE
Pylontech in Home Assistant Energy Dashboard

### DISCUSSION THREAD

**Discussion by meisterlampe** [hoylabs/OpenDTU-OnBattery#523] [Q&A] [answered]
Hi,

I guess many of you are using openDTU-onBattery and Pylontech Battery along with the home assistant, so maybe you can help me out. :)
My question: What is the best way to integrate the battery into the energy dashboard? Are there total counters for incoming and outgoing energy somewhere that I maybe missed?
Or are you manually calculating this within home assistant using the victron mppt and hoymiles counters? (in this case I'll have to wait for the support of my second victron mppt O: ) )

Thanks in advance.

**Comment by Somtom** [comment, marked as answer]
Hey @meisterlampe ,

I recently had the same issue and can share what I did to solve it.

In my case, I have a Pylontech US2000 connected with the DTU via CAN

### Step 1: Make sure you populate your data to MQTT

- In home assistant I am using the Mosquitto broker addon to setup a MQTT broker.
- Having done that, you need to make sure to enable the MQTT publishing in Open DTU:
   <img width="960" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/cc31b952-77ea-4469-8b0a-c654daed5219">
- I am using the MQTT Explorer addon to check whether I receive values. Apart from Pylontech information you get way more but here is an example on how the information for Pylontech specifically can look like (topic `solar/battery` in my case):
   <img width="394" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/f602c3dc-f91c-4d9a-afc8-8374044941af">

When you have set up everything correctly, the dtu devices (including the battery) and its sensors should show up as **MQTT** integration  in Home Assistant

### Step 2: Create custom helper sensors to measure the charge and discharge

Now we need 2 data points from the MQTT data to calculate the power that charges or discharges the battery:
* `voltage`
* `current`

What I did was that I created custom sensors. You can add them to the `/config/configuration.yaml` file (e.g. using a File editor addon).

Here is how my sensors look like:

```yaml
sensor:

  - platform: template
    sensors:
        # Current charge/discharge power of the battery
        pylontech_battery_power:
            unit_of_measurement: 'W'
            value_template: >-
              {{ states('sensor.battery_0001_battery_current')|float(0) * states('sensor.battery_0001_battery_voltage')|float(0) }}
              
        # Sensor for discharge power (if the value is negative)
        pylontech_battery_power_discharge:
          unit_of_measurement: 'W'
          value_template: >-
           {% if states('sensor.pylontech_battery_power')|float(0) < 0 %}
              {{ states('sensor.pylontech_battery_power')|float(0) * -1 }}
            {% else %}
              0
            {% endif %}
        
        # Sensor for charge power (if the value is positive)
        pylontech_battery_power_charge:
          unit_of_measurement: 'W'
          value_template: >-
            {% if states('sensor.pylontech_battery_power')|float(0) > 0 %}
              {{ states('sensor.pylontech_battery_power')|float(0) }}
            {% else %}
              0
            {% endif %}
```

Quick explanation:

* `pylontech_battery_power`: Current * Voltage -> Indicator for the power that charges or discharges the battery (depending on the sign)
* `pylontech_battery_power_discharge`: Discharge power (is 0 if charging and has a **positive** value in case there is a discharge going on)
* `pylontech_battery_power_charge`: Charge power (is 0 if discharging and has a positive value in case the battery is currently charged)


### Step 3: Create Rieman sum integral sensors" that can be used by the Energy Dashboard

Now that we have the sensors, you can create helper sensors. This also works In the Home Assistant interface when you go to `Settings -> Devices & Services -> Helpers (tabs at the top).

In my case I created 2 "Rieman sum integral sensors" 
<img width="1210" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/33bac1ec-9a39-4b6f-acf1-93bdb9f3ba48">

The settings could look something like this:

<img width="579" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/01b4bfae-233d-496b-a77c-6106ec6b8bb2">


### Step 4: Add your Rieman sum sensors to the energy dashboard

This is how you could do it:

<img width="373" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/7ff228e2-907d-4a32-8173-af6a90b6cb7c">

Note that even though there is a warning for me, it still works:

<img width="1197" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/29712801/2839f982-0efb-4343-9eaa-83774b21f92e">

**Reply by meisterlampe** [reply]
Wow. Thank you so much for this very detailed tutorial!
I suspected, that I have to do it within Home Assistant, but thought I had to calculate it all on my own (including some edge cases e.g. when there is a very large time gap between two received values.. ). Very cool, that Home Assistants has this built in.
Again: Thank you very much and I will follow your tutorial :)

**Reply by meisterlampe** [reply]
Hi again,
I tested your approach and it was working perfectly fine! Thanks again.

I'm using the new syntax for templates. The differences are not that big, but I post the the custom sensor configuration using the new syntax for others searching for this problem here:

```yaml
template:
 - sensor:
    # Current charge/discharge power of the battery
    - name: "Garage/PylontechBattery/Power"
      unique_id: "garage_pylontechbattery_power"
      icon: 'mdi:lightning-bolt'
      unit_of_measurement: 'W'
      state: >-
        {{ states('sensor.battery_0001_battery_current')|float(0) * states('sensor.battery_0001_battery_voltage')|float(0) }}
    # Sensor for discharge power (if the value is negative)
    - name: "Garage/PylontechBattery/PowerDischarge"
      unique_id: "garage_pylontechbattery_power_discharge"
      icon: 'mdi:lightning-bolt'
      unit_of_measurement: 'W'
      state: >-
        {% if states('sensor.garage_pylontechbattery_power')|float(0) < 0 %}
           {{ states('sensor.garage_pylontechbattery_power')|float(0) * -1 }}
        {% else %}
           0
        {% endif %}
    # Sensor for charge power (if the value is positive)
    - name: "Garage/PylontechBattery/PowerCharge"
      unique_id: "garage_pylontechbattery_power_charge"
      icon: 'mdi:lightning-bolt'
      unit_of_measurement: 'W'
      state: >-
        {% if states('sensor.garage_pylontechbattery_power')|float(0) > 0 %}
           {{ states('sensor.garage_pylontechbattery_power')|float(0) }}
        {% else %}
           0
        {% endif %}
```

**Reply by meisterlampe** [reply]
I know it is not that important, but I also found a way to get rid of the "unexpected device-class"-warnings:

Add the `device_class` to the customize-block in the homeassistant configuration.
It can look something like this:

```yaml
homeassistant:
  customize:
    sensor.pylontech_battery_charge_power_sum:
      device_class: "energy"
    sensor.pylontech_battery_discharge_power_sum:
      device_class: "energy"
``` 

After restarting (maybe reloading the config is enough?) the warnings should be gone.
